on:
  workflow_dispatch:
  schedule:
    # 在每天的北京时间 8:00和20:00 执行，一天执行一次
    - cron: '0 0 * * *'
    - cron: '0 12 * * *'
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Excavate
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: 1
